### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by schwim0341** [rignaneseleo/SlimSocial-for-Facebook#106]
As the title states, the lack of updates and general ignoring of the gh issue section makes it seem doomed.  Hope there's some life left in the project!

**Comment by tlaurion** [comment]
@rignaneseleo?

**Comment by rignaneseleo** [comment]
Hi guys, glad that some of you still show interest in the project.

I started the project 5 years ago (when I was 18yo) and in the meanwhile I changed technology I like to work with. Now I am focused mainly on Flutter.

My hope is to convert the app in Flutter in order to support it actively again, but at the moment the Webview is not ready yet. Nowadays I am just updating the app to fix little bugs or compatibility with new android version.

Everyone is more than welcome to work on my code which recently was totally translated in Kotlin.

I still belive in people privacy and right to run facebook without giving away all our data.

Stay tuned

**Comment by barbaMimmo** [comment]
SSF is a great app even if it's such small and innocent, but it would need for sure some more work on it. I am not a programmer myself, but I hope you'll find new helping hands here to join the workforce.
Iwas enthusiast finding your software on FDroid. It's the best solutions for who dislikes the ultra-heavy official FB apps and used to access Facebook only by a web browser.
I see you decided to switch from Java to Flutter and respect your decision, but please don't abandon this project in the meanwhile, since it's the only one which promises to be really lightweight and simple.
Happy coding everyone!

**Comment by rignaneseleo** [comment]
Version 4.0.0 is coming out today for BETA users.
Cheers
